// 📁 FILE PATH: lib/reports/farm-statement-pdf.ts
/**
 * lib/reports/farm-statement-pdf.ts
 *
 * WHY THIS EXISTS
 * ────────────────
 * PDF generation in this codebase existed in exactly one place —
 * app/api/cooperative/eudr/dds-export/route.ts — and it is coffee-DDS-only,
 * built for a cooperative officer filing EUDR paperwork. There was no
 * farmer-facing report a dairy, poultry, or small-ruminant farmer could
 * hand to a SACCO or bank loan officer as proof of income: "here is what
 * my herd/flock/farm earned over the last N months."
 *
 * This module is the shared layout: header/letterhead, a labeled summary
 * block, and a dated transaction table, laid out with the same
 * doc.text()/line-cursor approach dds-export uses (no external PDF
 * template dependency). Each enterprise's API route
 * (app/api/reports/farm-statement/route.ts) is responsible only for
 * shaping its own data into a FarmStatementInput — the actual PDF
 * drawing logic lives here once, not once per enterprise.
 *
 * Deliberately NOT the same document as the coffee DDS export: that one
 * is a compliance artifact (deforestation risk, plot geolocation) aimed
 * at a regulator/buyer. This one is a financial statement aimed at a
 * lender. Different audience, different content — sharing the drawing
 * primitives is enough; they don't need a shared data shape.
 */

import { jsPDF } from 'jspdf'

export interface StatementSummaryRow {
  label: string
  value: string
}

export interface StatementTransactionRow {
  date: string
  description: string
  quantity?: string
  amount: string
}

export interface FarmStatementInput {
  enterpriseLabel: string // e.g. "Dairy", "Poultry", "Small Ruminants"
  farmName: string
  ownerName: string | null
  county: string | null
  periodLabel: string // e.g. "1 Jan 2026 \u2013 16 Jul 2026"
  generatedAt: Date
  summary: StatementSummaryRow[]
  transactions: StatementTransactionRow[]
  transactionsTitle?: string // defaults to "Transactions"
  footerNote?: string
}

const PAGE_BOTTOM_MARGIN = 275
const LEFT_MARGIN = 14

export function buildFarmStatementPdf(input: FarmStatementInput): jsPDF {
  const doc = new jsPDF()

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(`${input.enterpriseLabel} Enterprise Statement`, LEFT_MARGIN, 18)

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(110)
  doc.text('Generated by the framedInsight farm management platform', LEFT_MARGIN, 24)

  doc.setTextColor(0)
  doc.setFontSize(11)
  let y = 36

  const line = (label: string, value: string) => {
    doc.setFont('helvetica', 'bold')
    doc.text(label, LEFT_MARGIN, y)
    doc.setFont('helvetica', 'normal')
    doc.text(value, 72, y)
    y += 7
  }

  line('Farm:', input.farmName)
  if (input.ownerName) line('Owner:', input.ownerName)
  if (input.county) line('County:', input.county)
  line('Period:', input.periodLabel)
  line('Generated:', input.generatedAt.toLocaleDateString('en-KE', { day: 'numeric', month: 'long', year: 'numeric' }))

  y += 4
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Summary', LEFT_MARGIN, y)
  y += 8
  doc.setFontSize(10)

  for (const row of input.summary) {
    if (y > PAGE_BOTTOM_MARGIN) { doc.addPage(); y = 18 }
    doc.setFont('helvetica', 'normal')
    doc.text(row.label, LEFT_MARGIN, y)
    doc.setFont('helvetica', 'bold')
    // Right-align the value against a fixed column so figures line up
    // down the page — matters for something meant to be skim-read by a
    // loan officer.
    doc.text(row.value, 196, y, { align: 'right' })
    y += 6.5
  }

  y += 6
  if (y > PAGE_BOTTOM_MARGIN) { doc.addPage(); y = 18 }
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text(input.transactionsTitle ?? 'Transactions', LEFT_MARGIN, y)
  y += 8

  doc.setFontSize(9)
  doc.setTextColor(110)
  doc.text('Date', LEFT_MARGIN, y)
  doc.text('Description', 46, y)
  doc.text('Amount (KES)', 196, y, { align: 'right' })
  doc.setTextColor(0)
  y += 5
  doc.setDrawColor(200)
  doc.line(LEFT_MARGIN, y - 2, 196, y - 2)

  doc.setFont('helvetica', 'normal')
  if (input.transactions.length === 0) {
    doc.setTextColor(130)
    doc.text('No transactions recorded for this period.', LEFT_MARGIN, y + 4)
    doc.setTextColor(0)
    y += 10
  } else {
    for (const t of input.transactions) {
      if (y > PAGE_BOTTOM_MARGIN) { doc.addPage(); y = 18 }
      doc.text(t.date, LEFT_MARGIN, y)
      const desc = t.quantity ? `${t.description} (${t.quantity})` : t.description
      doc.text(desc.length > 55 ? `${desc.slice(0, 52)}...` : desc, 46, y)
      doc.text(t.amount, 196, y, { align: 'right' })
      y += 6
    }
  }

  y += 8
  if (y > PAGE_BOTTOM_MARGIN) { doc.addPage(); y = 18 }
  doc.setFontSize(8)
  doc.setTextColor(130)
  const footer = input.footerNote
    ?? 'This statement summarizes farm records held by framedInsight on behalf of the farm owner named above. It is'
  doc.text(footer, LEFT_MARGIN, y); y += 5
  doc.text('provided for informational purposes (e.g. loan or SACCO applications) and is not an audited financial statement.', LEFT_MARGIN, y)

  return doc
}
